# 开发环境使用的Dockerfile
#
# 和非开发环境的主要区别在于：
# 1）依赖于宿主机做构建而容器内不做构建，直接从宿主机复制构建好的jar文件，开发迭代快速
# 2）构建出的容器使用完整的openjdk镜像，并可加入一些开发工具，开发时更方便

# 1. stage: build --------------------------------------------------------------
FROM openjdk:11.0.9.1-jdk

WORKDIR /opt
EXPOSE 8080

COPY target/*.jar ./app.jar

ENV SPRING_PROFILES_ACTIVE dev

ENTRYPOINT []

CMD [\
    "java", \
    "-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}", \
    "-Djava.security.egd=file:/dev/./urandom", \
    "-jar", "app.jar" \
]
