pipeline {
    agent { 
        node {
            customWorkspace '/server'
        }
    }
    stages {
        stage('Unit Test') {
            steps {
                sh './mvnw test'
            }
        }
        stage('Verify') {
            steps {
                sh './mvnw -B clean verify'
            }
        }
        stage('Build Image') {
            steps {
                sh "docker build -t engineer365/fleashop:${env.BUILD_ID} ."
            }
        }
    }
}
