pipeline {
    agent any
    stages {
        stage('Unit Test') {
            steps {
                sh 'cd server && ./mvnw test'
            }
        }
        stage('Verify') {
            steps {
                sh 'cd server && ./mvnw verify'
            }
        }
    }
}
